version: "3.8"
services:
  backend:
    build: /backend
    ports:
      - 5001:5001
    env_file: 
      - /backend/.env
  frontend:
    build: /frontend
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    depends_on:
      - backend